# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - composer update --no-interaction ${COMPOSER_OPTIONS}

script:
    - vendor/bin/phpspec run -fpretty

cache:
    directories:
        - $COMPOSER_CACHE_DIR
